name: Build UI

on:
  push:
    tags:
      - "**"
    paths-ignore:
      - "aleph/**"
      - "contrib/**"
      - "helm/**"
      - "mappings/**"
      - "site/**"
      - "docs/**"
      - "requirements.txt"
      - "requirements-dev.txt"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REPOSITORY_OWNER: wkspower

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup
        run: echo "ALEPH_SECRET=batman\n" >> aleph.env

      - name: Build development image
        uses: docker/build-push-action@v2
        with:
          context: ./ui
          platforms: linux/amd64,linux/arm64
          file: ui/Dockerfile.production
          push: false
          tags: "ghcr.io/wkspower/aleph-ui-production:${{ steps.extract_tag.outputs.tag }}"
  